### ISSUE TITLE
Rename class not properly applied "DunglasJsonLdApiAnnotatio"

### ISSUE THREAD

**Issue by sunel** [dunglas/php-schema#10]
Fatal error: Class 'SchemaOrgModel\AnnotationGenerator\DunglasJsonLdApiAnnotatio
nGenerator' not found in php-schema/src/SchemaOrgModel
/TypesGenerator.php on line 327

**Comment by dunglas** [comment]
Thanks for the report @sunel. Fixed in 4944d6465cfa9b7515dfbb3efcfcdccaa0d8157c.
