### ISSUE TITLE
Add optional config to enforce line lengths

### ISSUE THREAD

**Issue by stevenmaguire** [dunglas/php-schema#9]
As this project is responsible for generating classes to be included in other projects. Each of these projects may have different code standards.

I use PSR-2 coding styles in my projects. One of the requirements relates to line lengths. Instead of beginning the conversation of "enforcing code standards" and the nightmare that might be under there, I wanted to propose a hook to allow you to express some line limits and update the publishing tool to enforce these.

For now, I have to manually update these classes.

Thoughts?

**Comment by dunglas** [comment]
PHP Schema runs PHP CS Fixer on all generated at the end of the generation. It's possible to hook some custom rule directly as PHP CS Fixer fixers.

However, the generated code should already be conform to PSR-2 and the ligne length should be properly handled by PHP CS Fixer (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/629

Can you paste an example of invalid generated code?
